title: prompt2json
description: "Unix-style CLI that sends a system instruction, required JSON Schema, and text or file inputs to Vertex AI (Gemini models) and returns schema-validated JSON for easy batch processing."

remote_theme: just-the-docs/just-the-docs@v0.10.2
plugins:
  - jekyll-remote-theme

# External navigation links
nav_external_links:
  - title: prompt2json on GitHub
    url: https://github.com/UnitVectorY-Labs/prompt2json

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/UnitVectorY-Labs/prompt2json"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"